### ISSUE TITLE
Create Civilian Ship subclass

### ISSUE THREAD

**Issue by TheNulls** [OSU-CS361-W17/group10_project3#1]
We need to create a new class for the Dinghy and Clipper civilian ships that inherit properties from regular Ship.

**Comment by TheNulls** [comment]
Subclass created with limited functionality

**Comment by cascadeth** [comment]
added armor boolean to ship class
default in constructor, this is set to true
civship child class constructor sets this to false

**Comment by ghost** [comment]
autosink behavior is last addition to civilian ship subclass, implemented successfully
