### ISSUE TITLE
Finish UML Diagrams for Solution

### ISSUE THREAD

**Issue by ghost** [OSU-CS361-W17/group10_project3#12]
- [x] The first diagram should represent the class structure of your Battleship game from Project Stage 2.
  - [x] The second diagram should represent the expected class structure of your Battleship game with changes incorporated based upon the features listed above.
  - [x] The third diagram should represent the actual class structure of your final version after all of the requested features have been implemented.
  - The second and third diagram could potentially look the same, but they are much more likely to differ based upon your group's actual implementation.
  - The third diagram must match the version of your group's code that is submitted at the end of this assignment.
  - These diagrams can either be composed using UML modeling software, or drawn on paper (drawings should be labelled and legible).
  - [x] Scan and add this diagram to your group's Wiki pages (names should be added to indicate the author of each diagram).

**Comment by cascadeth** [comment]
All diagrams and UMLs uploaded.
