### ISSUE TITLE
Create stealth functionality for sub/battleship

### ISSUE THREAD

**Issue by TheNulls** [OSU-CS361-W17/group10_project3#5]

**Comment by cascadeth** [comment]
added stealth boolean
battleship and submarine ship constructors now have the stealth boolean set to true

**Comment by cascadeth** [comment]
tested scan on all ships
AirCC = true
BatShp = false
Clipper = true
Dinghy = true
Sub = false

Due to their proximity to each other(in the currently hard-coded computer ship layout):
AirCC & BatShp = true  (AirCC satisfies the "at least one ship detected")

testing complete
